name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: sinoru/actions-swiftlint@v6      
        env:
          DIFF_BASE: ${{ github.base_ref }}
        with:
          swiftlint-version: '5.7'
          swiftlint-args: --config .swiftlint
